name: Continuous Integration
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        cxx: [gcc]
        # cxx: [gcc, clang]
    runs-on: ubuntu-latest
    env:
      NIX_STDENV: ${{ matrix.cxx }}
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v24
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix flake check --print-build-logs
